keystore-path=secure/config.akt
keystore-masterkey-path=secure/wallet.key
keystore-password-path=secure/master.key

# Global directory search paths
app_search_dirs=#{empty dynamo_search_dirs ? '.' : dynamo_search_dirs};awa/plugins/awa-easymde;awa/plugins/awa-markedit;awa/plugins/awa-flots;awa/ada-keystore/akt

# AWA module configuration directory search paths
app.modules.dir=#{fn:composePath(app_search_dirs,'config')}

# Main XML configuration files that are read to configure the application.
app.config=awa.xml

# Additional XML configuration files that are read after 'app.config'
app.config.plugins=twinlife.xml

# The main application context path.
contextPath=

# Directory search paths for web files.
view.dir=#{fn:composePath(app_search_dirs,'web')}

# Directory search paths for bundle files.
bundle.dir=#{fn:composePath(app_search_dirs,'bundles')}

# Number of tasks dedicated to async job and event dispatching.
awa_dispatcher_count=1

# AWA counters module configuration
counters.counter_age_limit=1
counters.counter_limit=10

users.auth_key=test

workspaces.allow_workspace_create=true

view.ignore_spaces=false
view.escape_unknown_tags=true
view.ext=.html

# Login page
user.auth-filter.redirect=#{contextPath}/auth/login.html

# The base URL to construct URL to the application page.
app_url_base=http://localhost:8080#{contextPath}

# The application name
app_name=Twinlife

# The mail address of the application administrator
app_mail_from=Stephane Carrez
app_mail_name=Stephane.Carrez@twin.life

app_notify_mail=Stephane.Carrez@vacs.fr


# SMTP mail server
mail.smtp.host=localhost

# SMTP mail server port
mail.smtp.port=25

# Optional mail account for mail server
mail.smtp.user=

# Optional mail account password for mail server
mail.smtp.password=

twusers.jwt.mytwinlife.url=https://ws.mytwinlife.net
twusers.jwt.mytwinlife.kid=twinlife
twusers.jwt.mytwinlife.iss=dev.twin.life

twusers.jwt.twinme.url=https://ws.twin.me
twusers.jwt.twinme.kid=twinlife
twusers.jwt.twinme.iss=dev.twin.life

twusers.jwt.skred.url=https://ws.skred.mobi
twusers.jwt.skred.kid=twinlife
twusers.jwt.skred.iss=dev.twin.life


# Configuration for log4j
log4j.rootCategory=INFO,console,result

log4j.appender.console=Console
log4j.appender.console.level=ERROR
log4j.appender.console.layout=level-message

log4j.appender.result=File
log4j.appender.result.File=twinlife.log

# Logger configuration
log4j.logger.log=WARN
log4j.logger.Util.Properties=DEBUG
log4j.logger.Util.Log=WARN
log4j.logger.Util=DEBUG
log4j.logger.Util.Serialize.Mappers=WARN
log4j.logger.Util.Serialize.IO=INFO

log4j.logger.AWA=DEBUG
log4j.logger.ASF=DEBUG
log4j.logger.AWA.Modules=INFO

log4j.logger.ADO.Databases=INFO
log4j.logger.ASF.Views.Nodes.Reader=INFO
log4j.logger.AWA.Applications.Configs=WARN
log4j.logger.AWA.Modules=WARN

callback_url=http://mydomain.com/oauth
app_login_github=FALSE
app_login_email=TRUE
app_login_gitlab=FALSE
app_login_google=FALSE
app_login_methods=email
app_login_twitter=FALSE
app_login_openid=FALSE
app_login_register=TRUE
app_login_facebook=FALSE
dynamo_model_version=1
dynamo_build=113
