--  Twinlife Twincodes API
--  API for retrieving information about twincodes
--
--  The version of the OpenAPI document: 1.0.0
--
--
--  NOTE: This package is auto generated by OpenAPI-Generator 7.11.0-2024-11-24.
--  https://openapi-generator.tech
--  Do not edit the class manually.

package body Twinlife.Rest.Models is
   pragma Style_Checks ("-bmrIu");

   pragma Warnings (Off, "*use clause for package*");

   use OpenAPI.Streams;

   procedure Serialize (Into  : in out OpenAPI.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Twinlife.Rest.Models.ChangeInfo_Type) is
   begin
      Into.Start_Entity (Name);
      Serialize (Into, "major", Value.Major);
      Serialize (Into, "minor", Value.Minor);
      Into.End_Entity (Name);
   end Serialize;

   procedure Deserialize (From  : in OpenAPI.Value_Type;
                          Name  : in String;
                          Value : out Twinlife.Rest.Models.ChangeInfo_Type) is
      Object : OpenAPI.Value_Type;
   begin
      OpenAPI.Streams.Deserialize (From, Name, Object);
      OpenAPI.Streams.Deserialize (Object, "major", Value.Major);
      OpenAPI.Streams.Deserialize (Object, "minor", Value.Minor);
   end Deserialize;

   procedure Serialize (Into  : in out OpenAPI.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Twinlife.Rest.Models.DateInfo_Type) is
   begin
      Into.Start_Entity (Name);
      Into.Write_Entity ("year", Value.Year);
      Into.Write_Entity ("month", Value.Month);
      Into.Write_Entity ("day", Value.Day);
      Into.End_Entity (Name);
   end Serialize;

   procedure Deserialize (From  : in OpenAPI.Value_Type;
                          Name  : in String;
                          Value : out Twinlife.Rest.Models.DateInfo_Type) is
      Object : OpenAPI.Value_Type;
   begin
      OpenAPI.Streams.Deserialize (From, Name, Object);
      OpenAPI.Streams.Deserialize (Object, "year", Value.Year);
      OpenAPI.Streams.Deserialize (Object, "month", Value.Month);
      OpenAPI.Streams.Deserialize (Object, "day", Value.Day);
   end Deserialize;

   procedure Serialize (Into  : in out OpenAPI.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Twinlife.Rest.Models.TimeInfo_Type) is
   begin
      Into.Start_Entity (Name);
      Into.Write_Entity ("hour", Value.Hour);
      Into.Write_Entity ("minute", Value.Minute);
      Into.End_Entity (Name);
   end Serialize;

   procedure Deserialize (From  : in OpenAPI.Value_Type;
                          Name  : in String;
                          Value : out Twinlife.Rest.Models.TimeInfo_Type) is
      Object : OpenAPI.Value_Type;
   begin
      OpenAPI.Streams.Deserialize (From, Name, Object);
      OpenAPI.Streams.Deserialize (Object, "hour", Value.Hour);
      OpenAPI.Streams.Deserialize (Object, "minute", Value.Minute);
   end Deserialize;

   procedure Serialize (Into  : in out OpenAPI.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Twinlife.Rest.Models.DateTimeInfo_Type) is
   begin
      Into.Start_Entity (Name);
      Serialize (Into, "date", Value.Date);
      Serialize (Into, "time", Value.Time);
      Into.End_Entity (Name);
   end Serialize;

   procedure Deserialize (From  : in OpenAPI.Value_Type;
                          Name  : in String;
                          Value : out Twinlife.Rest.Models.DateTimeInfo_Type) is
      Object : OpenAPI.Value_Type;
   begin
      OpenAPI.Streams.Deserialize (From, Name, Object);
      Deserialize (Object, "date", Value.Date);
      Deserialize (Object, "time", Value.Time);
   end Deserialize;

   procedure Serialize (Into  : in out OpenAPI.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Twinlife.Rest.Models.TimeRange_Type) is
   begin
      Into.Start_Entity (Name);
      Serialize (Into, "start", Value.Start);
      Serialize (Into, "end", Value.P_End);
      Into.End_Entity (Name);
   end Serialize;

   procedure Serialize (Into  : in out OpenAPI.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in TimeRange_Type_Vectors.Vector) is
   begin
      Into.Start_Array (Name);
      for Item of Value loop
         Serialize (Into, "", Item);
      end loop;
      Into.End_Array (Name);
   end Serialize;

   procedure Deserialize (From  : in OpenAPI.Value_Type;
                          Name  : in String;
                          Value : out Twinlife.Rest.Models.TimeRange_Type) is
      Object : OpenAPI.Value_Type;
   begin
      OpenAPI.Streams.Deserialize (From, Name, Object);
      Deserialize (Object, "start", Value.Start);
      Deserialize (Object, "end", Value.P_End);
   end Deserialize;

   procedure Deserialize (From  : in OpenAPI.Value_Type;
                          Name  : in String;
                          Value : in out TimeRange_Type_Vectors.Vector) is
      List : OpenAPI.Value_Array_Type;
      Item : Twinlife.Rest.Models.TimeRange_Type;
   begin
      Value.Clear;
      OpenAPI.Streams.Deserialize (From, Name, List);
      for Data of List loop
         Deserialize (Data, "", Item);
         Value.Append (Item);
      end loop;
   end Deserialize;

   procedure Serialize (Into  : in out OpenAPI.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Twinlife.Rest.Models.Schedule_Type) is
   begin
      Into.Start_Entity (Name);
      Serialize (Into, "timeRanges", Value.Time_Ranges);
      Into.Write_Entity ("timeZone", Value.Time_Zone);
      Into.End_Entity (Name);
   end Serialize;

   procedure Deserialize (From  : in OpenAPI.Value_Type;
                          Name  : in String;
                          Value : out Twinlife.Rest.Models.Schedule_Type) is
      Object : OpenAPI.Value_Type;
   begin
      OpenAPI.Streams.Deserialize (From, Name, Object);
      Deserialize (Object, "timeRanges", Value.Time_Ranges);
      OpenAPI.Streams.Deserialize (Object, "timeZone", Value.Time_Zone);
   end Deserialize;

   procedure Serialize (Into  : in out OpenAPI.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Twinlife.Rest.Models.Twincode_Type) is
   begin
      Into.Start_Entity (Name);
      Into.Write_Entity ("name", Value.Name);
      Into.Write_Entity ("description", Value.Description);
      Into.Write_Entity ("avatarId", Value.Avatar_Id);
      if not Value.Public_Key.Is_Null then
         Into.Write_Entity ("publicKey", Value.Public_Key);
      end if;
      Into.Write_Entity ("audio", Value.Audio);
      Into.Write_Entity ("video", Value.Video);
      Into.Write_Entity ("transfer", Value.Transfer);
      Into.Write_Entity ("group", Value.Group);
      Into.Write_Entity ("conference", Value.Conference);
      Serialize (Into, "schedule", Value.Schedule);
      Into.End_Entity (Name);
   end Serialize;

   procedure Deserialize (From  : in OpenAPI.Value_Type;
                          Name  : in String;
                          Value : out Twinlife.Rest.Models.Twincode_Type) is
      Object : OpenAPI.Value_Type;
   begin
      OpenAPI.Streams.Deserialize (From, Name, Object);
      OpenAPI.Streams.Deserialize (Object, "name", Value.Name);
      OpenAPI.Streams.Deserialize (Object, "description", Value.Description);
      OpenAPI.Streams.Deserialize (Object, "avatarId", Value.Avatar_Id);
      OpenAPI.Streams.Deserialize (Object, "publicKey", Value.Public_Key);
      OpenAPI.Streams.Deserialize (Object, "audio", Value.Audio);
      OpenAPI.Streams.Deserialize (Object, "video", Value.Video);
      OpenAPI.Streams.Deserialize (Object, "transfer", Value.Transfer);
      OpenAPI.Streams.Deserialize (Object, "group", Value.Group);
      OpenAPI.Streams.Deserialize (Object, "conference", Value.Conference);
      Deserialize (Object, "schedule", Value.Schedule);
   end Deserialize;

   procedure Serialize (Into  : in out OpenAPI.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Twinlife.Rest.Models.TwinmeInfo_Type) is
   begin
      Into.Start_Entity (Name);
      Into.Write_Entity ("version", Value.Version);
      if not Value.Min_Sdk.Is_Null then
         Into.Write_Entity ("minSdk", Value.Min_Sdk);
      end if;
      if not Value.Size.Is_Null then
         Into.Write_Entity ("size", Value.Size);
      end if;
      if not Value.Sha_256sum.Is_Null then
         Into.Write_Entity ("sha256sum", Value.Sha_256sum);
      end if;
      Serialize (Into, "images", Value.Images);
      Serialize (Into, "images_dark", Value.Images_Dark);
      Serialize (Into, "changes", Value.Changes);
      Into.End_Entity (Name);
   end Serialize;

   procedure Deserialize (From  : in OpenAPI.Value_Type;
                          Name  : in String;
                          Value : out Twinlife.Rest.Models.TwinmeInfo_Type) is
      Object : OpenAPI.Value_Type;
   begin
      OpenAPI.Streams.Deserialize (From, Name, Object);
      OpenAPI.Streams.Deserialize (Object, "version", Value.Version);
      OpenAPI.Streams.Deserialize (Object, "minSdk", Value.Min_Sdk);
      OpenAPI.Streams.Deserialize (Object, "size", Value.Size);
      OpenAPI.Streams.Deserialize (Object, "sha256sum", Value.Sha_256sum);
      OpenAPI.Streams.Deserialize (Object, "images", Value.Images);
      OpenAPI.Streams.Deserialize (Object, "images_dark", Value.Images_Dark);
      Deserialize (Object, "changes", Value.Changes);
   end Deserialize;


end Twinlife.Rest.Models;
