--  Twinlife Twincodes API
--  API for retrieving information about twincodes
--
--  The version of the OpenAPI document: 1.0.0
--
--
--  NOTE: This package is auto generated by OpenAPI-Generator 7.11.0-2024-11-24.
--  https://openapi-generator.tech
--  Do not edit the class manually.

with OpenAPI.Streams;
with Ada.Containers.Vectors;
package Twinlife.Rest.Models is
   pragma Style_Checks ("-bmrIu");




   type ChangeInfo_Type is
     record
       Major : OpenAPI.UString_Vector;
       Minor : OpenAPI.UString_Vector;
     end record;



   procedure Serialize (Into  : in out OpenAPI.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Twinlife.Rest.Models.ChangeInfo_Type);
   procedure Deserialize (From  : in OpenAPI.Value_Type;
                          Name  : in String;
                          Value : out Twinlife.Rest.Models.ChangeInfo_Type);





   type DateInfo_Type is
     record
       Year : Integer;
       Month : Integer;
       Day : Integer;
     end record;



   procedure Serialize (Into  : in out OpenAPI.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Twinlife.Rest.Models.DateInfo_Type);
   procedure Deserialize (From  : in OpenAPI.Value_Type;
                          Name  : in String;
                          Value : out Twinlife.Rest.Models.DateInfo_Type);





   type TimeInfo_Type is
     record
       Hour : Integer;
       Minute : Integer;
     end record;



   procedure Serialize (Into  : in out OpenAPI.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Twinlife.Rest.Models.TimeInfo_Type);
   procedure Deserialize (From  : in OpenAPI.Value_Type;
                          Name  : in String;
                          Value : out Twinlife.Rest.Models.TimeInfo_Type);





   type DateTimeInfo_Type is
     record
       Date : Twinlife.Rest.Models.DateInfo_Type;
       Time : Twinlife.Rest.Models.TimeInfo_Type;
     end record;



   procedure Serialize (Into  : in out OpenAPI.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Twinlife.Rest.Models.DateTimeInfo_Type);
   procedure Deserialize (From  : in OpenAPI.Value_Type;
                          Name  : in String;
                          Value : out Twinlife.Rest.Models.DateTimeInfo_Type);





   type TimeRange_Type is
     record
       Start : Twinlife.Rest.Models.DateTimeInfo_Type;
       P_End : Twinlife.Rest.Models.DateTimeInfo_Type;
     end record;


   package TimeRange_Type_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => Twinlife.Rest.Models.TimeRange_Type);

   procedure Serialize (Into  : in out OpenAPI.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Twinlife.Rest.Models.TimeRange_Type);
   procedure Serialize (Into  : in out OpenAPI.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in TimeRange_Type_Vectors.Vector);
   procedure Deserialize (From  : in OpenAPI.Value_Type;
                          Name  : in String;
                          Value : out Twinlife.Rest.Models.TimeRange_Type);
   procedure Deserialize (From  : in OpenAPI.Value_Type;
                          Name  : in String;
                          Value : in out TimeRange_Type_Vectors.Vector);




   type Schedule_Type is
     record
       Time_Ranges : Twinlife.Rest.Models.TimeRange_Type_Vectors.Vector;
       Time_Zone : OpenAPI.UString;
     end record;



   procedure Serialize (Into  : in out OpenAPI.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Twinlife.Rest.Models.Schedule_Type);
   procedure Deserialize (From  : in OpenAPI.Value_Type;
                          Name  : in String;
                          Value : out Twinlife.Rest.Models.Schedule_Type);





   type Twincode_Type is
     record
       Name : OpenAPI.UString;
       Description : OpenAPI.UString;
       Avatar_Id : OpenAPI.UString;
       Public_Key : OpenAPI.Nullable_UString;
       Audio : Boolean;
       Video : Boolean;
       Transfer : Boolean;
       Group : Boolean;
       Conference : Boolean;
       Schedule : Twinlife.Rest.Models.Schedule_Type;
     end record;



   procedure Serialize (Into  : in out OpenAPI.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Twinlife.Rest.Models.Twincode_Type);
   procedure Deserialize (From  : in OpenAPI.Value_Type;
                          Name  : in String;
                          Value : out Twinlife.Rest.Models.Twincode_Type);





   type TwinmeInfo_Type is
     record
       Version : OpenAPI.UString;
       Min_Sdk : OpenAPI.Nullable_Integer;
       Size : OpenAPI.Nullable_Integer;
       Sha_256sum : OpenAPI.Nullable_UString;
       Images : OpenAPI.UString_Vector;
       Images_Dark : OpenAPI.UString_Vector;
       Changes : Twinlife.Rest.Models.ChangeInfo_Type;
     end record;



   procedure Serialize (Into  : in out OpenAPI.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in Twinlife.Rest.Models.TwinmeInfo_Type);
   procedure Deserialize (From  : in OpenAPI.Value_Type;
                          Name  : in String;
                          Value : out Twinlife.Rest.Models.TwinmeInfo_Type);



end Twinlife.Rest.Models;
