#!/bin/sh
RDIR=`dirname $0`
RDIR=`realpath $RDIR`
RDIR=`realpath $RDIR`
CDIR=/etc/twindev
DDIR=/opt/data
DIR=/opt/twindev

export LD_LIBRARY_PATH=$DIR/lib
export PATH="$DIR/bin:$PATH"

cd $DIR
test -d storage || ln -s $DDIR/storage
test -d upload || ln -s $DDIR/upload
test -d web/preview || ln -s $DDIR/preview web/preview
exec $DIR/bin/twinlife-server --config $CDIR/secure.properties $*

