--  Twinlife Twincodes API
--  API for retrieving information about twincodes
--
--  The version of the OpenAPI document: 1.0.0
--
--
--  NOTE: This package is auto generated by OpenAPI-Generator 7.11.0-2024-11-24.
--  https://openapi-generator.tech
--  Do not edit the class manually.

pragma Warnings (Off, "*is not referenced");
with OpenAPI.Streams;
package body Twinlife.Rest.Clients is
   pragma Style_Checks ("-bmrIu");

   Media_List_1 : constant OpenAPI.Mime_List := (
     1 => OpenAPI.Mime_Json   );


   --  Get twincode information from a miniCode
   --  Retrieve details about a specific twincode
   procedure Get_Mini_Code
      (Client : in out Client_Type;
       Mini_Code : in OpenAPI.UString;
       Result : out Twinlife.Rest.Models.Twincode_Type) is
      URI   : OpenAPI.Clients.URI_Type;
      Reply : OpenAPI.Value_Type;
   begin
      Client.Set_Accept (Media_List_1);


      URI.Set_Path ("/rest/api/minicodes/{miniCode}");
      URI.Set_Path_Param ("miniCode", Mini_Code);
      Client.Call (OpenAPI.Clients.GET, URI, Reply);
      Twinlife.Rest.Models.Deserialize (Reply, "", Result);
   end Get_Mini_Code;

   --  Get twincode information
   --  Retrieve details about a specific twincode
   procedure Get_Twincode
      (Client : in out Client_Type;
       Twincode_Id : in OpenAPI.UString;
       Result : out Twinlife.Rest.Models.Twincode_Type) is
      URI   : OpenAPI.Clients.URI_Type;
      Reply : OpenAPI.Value_Type;
   begin
      Client.Set_Accept (Media_List_1);


      URI.Set_Path ("/rest/api/twincodes/{twincodeId}");
      URI.Set_Path_Param ("twincodeId", Twincode_Id);
      Client.Call (OpenAPI.Clients.GET, URI, Reply);
      Twinlife.Rest.Models.Deserialize (Reply, "", Result);
   end Get_Twincode;

   --  Get Twinme application information
   --  Retrieve the latest Twinme application details including version, size, and changelog
   procedure Get_Version
      (Client : in out Client_Type;
       Name : in OpenAPI.UString;
       Result : out Twinlife.Rest.Models.TwinmeInfo_Type) is
      URI   : OpenAPI.Clients.URI_Type;
      Reply : OpenAPI.Value_Type;
   begin
      Client.Set_Accept (Media_List_1);


      URI.Set_Path ("/download/{name}");
      URI.Set_Path_Param ("name", Name);
      Client.Call (OpenAPI.Clients.GET, URI, Reply);
      Twinlife.Rest.Models.Deserialize (Reply, "", Result);
   end Get_Version;
end Twinlife.Rest.Clients;
