--  Twinlife Twincodes API
--  API for retrieving information about twincodes
--
--  The version of the OpenAPI document: 1.0.0
--
--
--  NOTE: This package is auto generated by OpenAPI-Generator 7.11.0-2024-11-24.
--  https://openapi-generator.tech
--  Do not edit the class manually.

with Twinlife.Rest.Models;
with OpenAPI.Clients;
package Twinlife.Rest.Clients is
   pragma Style_Checks ("-bmrIu");

   type Client_Type is new OpenAPI.Clients.Client_Type with null record;

   --  Get twincode information from a miniCode
   --  Retrieve details about a specific twincode
   procedure Get_Mini_Code
      (Client : in out Client_Type;
       Mini_Code : in OpenAPI.UString;
       Result : out Twinlife.Rest.Models.Twincode_Type);

   --  Get twincode information
   --  Retrieve details about a specific twincode
   procedure Get_Twincode
      (Client : in out Client_Type;
       Twincode_Id : in OpenAPI.UString;
       Result : out Twinlife.Rest.Models.Twincode_Type);

   --  Get Twinme application information
   --  Retrieve the latest Twinme application details including version, size, and changelog
   procedure Get_Version
      (Client : in out Client_Type;
       Name : in OpenAPI.UString;
       Result : out Twinlife.Rest.Models.TwinmeInfo_Type);

end Twinlife.Rest.Clients;
